<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DefaultSeeder extends Seeder
{
    public function run(): void
    {
        // Admin Yayasan
        DB::table('admin_yayasan')->insert([
            [
                'admin_yayasan_id' => 1,
                'username' => 'adminyayasan1',
                'email' => 'adminyayasan1@gmail.com',
                'password' => Hash::make('adminyayasan1'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_yayasan_id' => 2,
                'username' => 'adminyayasan2',
                'email' => 'adminyayasan2@gmail.com',
                'password' => Hash::make('adminyayasan2'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Yayasan
        DB::table('yayasan')->insert([
            [
                'yayasan_id' => 1,
                'nama_yayasan' => 'Yayasan Pendidikan Advent Papua',
                'alamat' => 'Jln. Lumba-Lumba, Dok V Atas, -, Kec. Jayapura Selatan, Kota Jayapura Prov. Papua',
                'admin_yayasan_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Sekolah
        DB::table('sekolah')->insert([
            [
                'sekolah_id' => 1,
                'yayasan_id' => 1,
                'nama_sekolah' => 'SD Advent Doyo Baru',
                'alamat' => 'Bambar, Distrik Waibu, Kabupaten Jayapura, Papua 99352',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sekolah_id' => 2,
                'yayasan_id' => 1,
                'nama_sekolah' => 'SMP Advent Doyo Baru',
                'alamat' => 'Jl. Raya Doyo Baru, Doyo Baru, Distrik Waibu, Kabupaten Jayapura, Papua 99352',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sekolah_id' => 3,
                'yayasan_id' => 1,
                'nama_sekolah' => 'SMA Advent Doyo Baru',
                'alamat' => 'Jl. Raya Doyo Baru, Doyo Baru, Distrik Waibu, Kabupaten Jayapura, Papua 99352',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Admin Sekolah
        DB::table('admin_sekolah')->insert([
            [
                'admin_sekolah_id' => 1,
                'username' => 'adminsekolah1',
                'email' => 'adminsekolah1@gmail.com',
                'password' => Hash::make('adminsekolah1'),
                'sekolah_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'admin_sekolah_id' => 2,
                'username' => 'adminsekolah2',
                'email' => 'adminsekolah2@gmail.com',
                'password' => Hash::make('adminsekolah2'),
                'sekolah_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Guru
        DB::table('user_guru')->insert([
            [
                'user_guru_id' => 1,
                'sekolah_id' => 1,
                'username' => 'guru1',
                'email' => 'guru1@gmail.com',
                'password' => Hash::make('guru1'),
                'nama' => 'Guru 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_guru_id' => 2,
                'sekolah_id' => 2,
                'username' => 'guru2',
                'email' => 'guru2@gmail.com',
                'password' => Hash::make('guru2'),
                'nama' => 'Guru 2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
                        [
                'user_guru_id' => 3,
                'sekolah_id' => 3,
                'username' => 'guru3',
                'email' => 'guru3@gmail.com',
                'password' => Hash::make('guru3'),
                'nama' => 'Guru 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Kelas
        DB::table('kelas')->insert([
            [
                'kelas_id' => 1,
                'sekolah_id' => 1,
                'nama_kelas' => 'Kelas 6A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kelas_id' => 2,
                'sekolah_id' => 2,
                'nama_kelas' => 'Kelas 9D',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kelas_id' => 3,
                'sekolah_id' => 3,
                'nama_kelas' => 'Kelas 12 IPS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Siswa SD Kelas 6A
        DB::table('siswa')->insert([
            [
                'siswa_id' => 1,
                'kelas_id' => 1,
                'nis' => 'NIS001',
                'nama_siswa' => 'Abraham',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 2,
                'kelas_id' => 1,
                'nis' => 'NIS002',
                'nama_siswa' => 'Arrybal',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 3,
                'kelas_id' => 1,
                'nis' => 'NIS003',
                'nama_siswa' => 'Bebi',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 4,
                'kelas_id' => 1,
                'nis' => 'NIS004',
                'nama_siswa' => 'Bonand',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 5,
                'kelas_id' => 1,
                'nis' => 'NIS005',
                'nama_siswa' => 'Brayen',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 6,
                'kelas_id' => 1,
                'nis' => 'NIS006',
                'nama_siswa' => 'Christine Bethelsiya',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 7,
                'kelas_id' => 1,
                'nis' => 'NIS007',
                'nama_siswa' => 'Christine Treselin',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 8,
                'kelas_id' => 1,
                'nis' => 'NIS008',
                'nama_siswa' => 'Cornelisha',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 9,
                'kelas_id' => 1,
                'nis' => 'NIS009',
                'nama_siswa' => 'Dorkas',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 10,
                'kelas_id' => 1,
                'nis' => 'NIS010',
                'nama_siswa' => 'Gabriela',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 11,
                'kelas_id' => 1,
                'nis' => 'NIS011',
                'nama_siswa' => 'Ganni',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 12,
                'kelas_id' => 1,
                'nis' => 'NIS012',
                'nama_siswa' => 'Hendrik',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 13,
                'kelas_id' => 1,
                'nis' => 'NIS013',
                'nama_siswa' => 'Jeremi',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 14,
                'kelas_id' => 1,
                'nis' => 'NIS014',
                'nama_siswa' => 'Jionta',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 15,
                'kelas_id' => 1,
                'nis' => 'NIS015',
                'nama_siswa' => 'Joulswilliam',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 16,
                'kelas_id' => 1,
                'nis' => 'NIS016',
                'nama_siswa' => 'Juanike',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 17,
                'kelas_id' => 1,
                'nis' => 'NIS017',
                'nama_siswa' => 'Kenes',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 18,
                'kelas_id' => 1,
                'nis' => 'NIS018',
                'nama_siswa' => 'Lionel',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 19,
                'kelas_id' => 1,
                'nis' => 'NIS019',
                'nama_siswa' => 'Lovely',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 20,
                'kelas_id' => 1,
                'nis' => 'NIS020',
                'nama_siswa' => 'Mcloivta',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 21,
                'kelas_id' => 1,
                'nis' => 'NIS021',
                'nama_siswa' => 'Melan',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 22,
                'kelas_id' => 1,
                'nis' => 'NIS022',
                'nama_siswa' => 'Melky',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 23,
                'kelas_id' => 1,
                'nis' => 'NIS023',
                'nama_siswa' => 'Oliver',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 24,
                'kelas_id' => 1,
                'nis' => 'NIS024',
                'nama_siswa' => 'Rafael',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 25,
                'kelas_id' => 1,
                'nis' => 'NIS025',
                'nama_siswa' => 'Risad',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 26,
                'kelas_id' => 1,
                'nis' => 'NIS026',
                'nama_siswa' => 'Sandolfon',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 27,
                'kelas_id' => 1,
                'nis' => 'NIS027',
                'nama_siswa' => 'Teresiana',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 28,
                'kelas_id' => 1,
                'nis' => 'NIS028',
                'nama_siswa' => 'Tinggis',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 29,
                'kelas_id' => 1,
                'nis' => 'NIS029',
                'nama_siswa' => 'Ulam',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 30,
                'kelas_id' => 1,
                'nis' => 'NIS030',
                'nama_siswa' => 'Victoria',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 31,
                'kelas_id' => 1,
                'nis' => 'NIS031',
                'nama_siswa' => 'Vincent De Mario',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 32,
                'kelas_id' => 1,
                'nis' => 'NIS032',
                'nama_siswa' => 'Wenewaga',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 33,
                'kelas_id' => 1,
                'nis' => 'NIS033',
                'nama_siswa' => 'Zahsyani',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 34,
                'kelas_id' => 1,
                'nis' => 'NIS034',
                'nama_siswa' => 'Adeeva',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 35,
                'kelas_id' => 1,
                'nis' => 'NIS035',
                'nama_siswa' => 'Yuliya',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 36,
                'kelas_id' => 1,
                'nis' => 'NIS036',
                'nama_siswa' => 'Hein',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Siswa SMP Kelas 9D
        DB::table('siswa')->insert([
            [
                'siswa_id' => 37,
                'kelas_id' => 2,
                'nis' => 'NIS037',
                'nama_siswa' => 'Alfredo',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 38,
                'kelas_id' => 2,
                'nis' => 'NIS038',
                'nama_siswa' => 'Anggely',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 39,
                'kelas_id' => 2,
                'nis' => 'NIS039',
                'nama_siswa' => 'Averia',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 40,
                'kelas_id' => 2,
                'nis' => 'NIS040',
                'nama_siswa' => 'Eris',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 41,
                'kelas_id' => 2,
                'nis' => 'NIS041',
                'nama_siswa' => 'Ester',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 42,
                'kelas_id' => 2,
                'nis' => 'NIS042',
                'nama_siswa' => 'Farel',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 43,
                'kelas_id' => 2,
                'nis' => 'NIS043',
                'nama_siswa' => 'Florhendsia',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 44,
                'kelas_id' => 2,
                'nis' => 'NIS044',
                'nama_siswa' => 'Imelda',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 45,
                'kelas_id' => 2,
                'nis' => 'NIS045',
                'nama_siswa' => 'Indah',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 46,
                'kelas_id' => 2,
                'nis' => 'NIS046',
                'nama_siswa' => 'Jacklin',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 47,
                'kelas_id' => 2,
                'nis' => 'NIS047',
                'nama_siswa' => 'Jerry',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 48,
                'kelas_id' => 2,
                'nis' => 'NIS048',
                'nama_siswa' => 'Yeschika',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 49,
                'kelas_id' => 2,
                'nis' => 'NIS049',
                'nama_siswa' => 'Jossua',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 50,
                'kelas_id' => 2,
                'nis' => 'NIS050',
                'nama_siswa' => 'Junior',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 51,
                'kelas_id' => 2,
                'nis' => 'NIS051',
                'nama_siswa' => 'Kabayas',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 52,
                'kelas_id' => 2,
                'nis' => 'NIS052',
                'nama_siswa' => 'Marchella',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 53,
                'kelas_id' => 2,
                'nis' => 'NIS053',
                'nama_siswa' => 'Maryolen',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 54,
                'kelas_id' => 2,
                'nis' => 'NIS054',
                'nama_siswa' => 'Miracle',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 55,
                'kelas_id' => 2,
                'nis' => 'NIS055',
                'nama_siswa' => 'Nethaniah',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 56,
                'kelas_id' => 2,
                'nis' => 'NIS056',
                'nama_siswa' => 'Princess',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 57,
                'kelas_id' => 2,
                'nis' => 'NIS057',
                'nama_siswa' => 'Queen',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 58,
                'kelas_id' => 2,
                'nis' => 'NIS058',
                'nama_siswa' => 'Revan',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 59,
                'kelas_id' => 2,
                'nis' => 'NIS059',
                'nama_siswa' => 'Dolvinus',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 60,
                'kelas_id' => 2,
                'nis' => 'NIS060',
                'nama_siswa' => 'Steenly',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 61,
                'kelas_id' => 2,
                'nis' => 'NIS061',
                'nama_siswa' => 'Stefanus',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 62,
                'kelas_id' => 2,
                'nis' => 'NIS062',
                'nama_siswa' => 'Vrinska',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 63,
                'kelas_id' => 2,
                'nis' => 'NIS063',
                'nama_siswa' => 'Welmince',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 64,
                'kelas_id' => 2,
                'nis' => 'NIS064',
                'nama_siswa' => 'Yosafat',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 65,
                'kelas_id' => 2,
                'nis' => 'NIS065',
                'nama_siswa' => 'Joenya',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 66,
                'kelas_id' => 2,
                'nis' => 'NIS066',
                'nama_siswa' => 'Queensy',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Siswa SMA Kelas 12 IPS
        DB::table('siswa')->insert([
            [
                'siswa_id' => 67,
                'kelas_id' => 3,
                'nis' => 'NIS067',
                'nama_siswa' => 'Pebjud',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 68,
                'kelas_id' => 3,
                'nis' => 'NIS068',
                'nama_siswa' => 'Septinus',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 69,
                'kelas_id' => 3,
                'nis' => 'NIS069',
                'nama_siswa' => 'Bastian',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 70,
                'kelas_id' => 3,
                'nis' => 'NIS070',
                'nama_siswa' => 'Ester',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 71,
                'kelas_id' => 3,
                'nis' => 'NIS071',
                'nama_siswa' => 'Etiron',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 72,
                'kelas_id' => 3,
                'nis' => 'NIS072',
                'nama_siswa' => 'Fabiano',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 73,
                'kelas_id' => 3,
                'nis' => 'NIS073',
                'nama_siswa' => 'Foniria',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 74,
                'kelas_id' => 3,
                'nis' => 'NIS074',
                'nama_siswa' => 'Hennike',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 75,
                'kelas_id' => 3,
                'nis' => 'NIS075',
                'nama_siswa' => 'Imanuel',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 76,
                'kelas_id' => 3,
                'nis' => 'NIS076',
                'nama_siswa' => 'Jack',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 77,
                'kelas_id' => 3,
                'nis' => 'NIS077',
                'nama_siswa' => 'Janet',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 78,
                'kelas_id' => 3,
                'nis' => 'NIS078',
                'nama_siswa' => 'Maria',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 79,
                'kelas_id' => 3,
                'nis' => 'NIS079',
                'nama_siswa' => 'Mattheuw',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 80,
                'kelas_id' => 3,
                'nis' => 'NIS080',
                'nama_siswa' => 'Naomi',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 81,
                'kelas_id' => 3,
                'nis' => 'NIS081',
                'nama_siswa' => 'Orpa',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 82,
                'kelas_id' => 3,
                'nis' => 'NIS082',
                'nama_siswa' => 'Panius',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 83,
                'kelas_id' => 3,
                'nis' => 'NIS083',
                'nama_siswa' => 'Paul',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 84,
                'kelas_id' => 3,
                'nis' => 'NIS084',
                'nama_siswa' => 'Rey',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 85,
                'kelas_id' => 3,
                'nis' => 'NIS085',
                'nama_siswa' => 'Ricko',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 86,
                'kelas_id' => 3,
                'nis' => 'NIS086',
                'nama_siswa' => 'Sanly',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 87,
                'kelas_id' => 3,
                'nis' => 'NIS087',
                'nama_siswa' => 'Seblum',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 88,
                'kelas_id' => 3,
                'nis' => 'NIS088',
                'nama_siswa' => 'Tonci',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 89,
                'kelas_id' => 3,
                'nis' => 'NIS089',
                'nama_siswa' => 'Venscha',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 90,
                'kelas_id' => 3,
                'nis' => 'NIS090',
                'nama_siswa' => 'Victor',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 91,
                'kelas_id' => 3,
                'nis' => 'NIS091',
                'nama_siswa' => 'Windy',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 92,
                'kelas_id' => 3,
                'nis' => 'NIS092',
                'nama_siswa' => 'Yeni',
                'jenis_kelamin' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 93,
                'kelas_id' => 3,
                'nis' => 'NIS093',
                'nama_siswa' => 'Yesaya',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 94,
                'kelas_id' => 3,
                'nis' => 'NIS094',
                'nama_siswa' => 'Yotam',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 95,
                'kelas_id' => 3,
                'nis' => 'NIS095',
                'nama_siswa' => 'Yusup',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'siswa_id' => 96,
                'kelas_id' => 3,
                'nis' => 'NIS096',
                'nama_siswa' => 'Phillip',
                'jenis_kelamin' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Kriteria SD
        DB::table('kriteria')->insert([
            ['sekolah_id' => 1, 'kode_kriteria' => 'A1',  'nama_kriteria' => 'Nilai Rata-rata Semester 1',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A2',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 1',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A3',  'nama_kriteria' => 'Absensi Semester 1',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A4',  'nama_kriteria' => 'Nilai Rata-rata Semester 2',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A5',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 2',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A6',  'nama_kriteria' => 'Absensi Semester 2',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A7',  'nama_kriteria' => 'Nilai Rata-rata Semester 3',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A8',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 3',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A9',  'nama_kriteria' => 'Absensi Semester 3',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A10', 'nama_kriteria' => 'Nilai Rata-rata Semester 4',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A11', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 4',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A12', 'nama_kriteria' => 'Absensi Semester 4',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A13', 'nama_kriteria' => 'Nilai Rata-rata Semester 5',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A14', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 5',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A15', 'nama_kriteria' => 'Absensi Semester 5',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A16', 'nama_kriteria' => 'Nilai Rata-rata Semester 6',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A17', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 6',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A18', 'nama_kriteria' => 'Absensi Semester 6',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A19', 'nama_kriteria' => 'Nilai Rata-rata Semester 7',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A20', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 7',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A21', 'nama_kriteria' => 'Absensi Semester 7',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A22', 'nama_kriteria' => 'Nilai Rata-rata Semester 8',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A23', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 8',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A24', 'nama_kriteria' => 'Absensi Semester 8',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A25', 'nama_kriteria' => 'Nilai Rata-rata Semester 9',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A26', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 9',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A27', 'nama_kriteria' => 'Absensi Semester 9',  'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A28', 'nama_kriteria' => 'Nilai Rata-rata Semester 10', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A29', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 10', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A30', 'nama_kriteria' => 'Absensi Semester 10', 'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A31', 'nama_kriteria' => 'Nilai Rata-rata Semester 11', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A32', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 11', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A33', 'nama_kriteria' => 'Absensi Semester 11', 'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A34', 'nama_kriteria' => 'Nilai Rata-rata Semester 12', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A35', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 12', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A36', 'nama_kriteria' => 'Absensi Semester 12', 'jenis' => 'cost', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 1, 'kode_kriteria' => 'A37', 'nama_kriteria' => 'Prestasi', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Kriteria SMP
        DB::table('kriteria')->insert([
            ['sekolah_id' => 2, 'kode_kriteria' => 'A1',  'nama_kriteria' => 'Nilai Rata-rata Semester 1',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A2',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 1',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A3',  'nama_kriteria' => 'Absensi Semester 1',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A4',  'nama_kriteria' => 'Nilai Rata-rata Semester 2',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A5',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 2',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A6',  'nama_kriteria' => 'Absensi Semester 2',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A7',  'nama_kriteria' => 'Nilai Rata-rata Semester 3',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A8',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 3',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A9',  'nama_kriteria' => 'Absensi Semester 3',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A10', 'nama_kriteria' => 'Nilai Rata-rata Semester 4',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A11', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 4',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A12', 'nama_kriteria' => 'Absensi Semester 4',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A13', 'nama_kriteria' => 'Nilai Rata-rata Semester 5',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A14', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 5',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A15', 'nama_kriteria' => 'Absensi Semester 5',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A16', 'nama_kriteria' => 'Nilai Rata-rata Semester 6',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A17', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 6',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A18', 'nama_kriteria' => 'Absensi Semester 6',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 2, 'kode_kriteria' => 'A19', 'nama_kriteria' => 'Prestasi', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Kriteria SMA
        DB::table('kriteria')->insert([
            ['sekolah_id' => 3, 'kode_kriteria' => 'A1',  'nama_kriteria' => 'Nilai Rata-rata Semester 1',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A2',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 1',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A3',  'nama_kriteria' => 'Absensi Semester 1',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A4',  'nama_kriteria' => 'Nilai Rata-rata Semester 2',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A5',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 2',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A6',  'nama_kriteria' => 'Absensi Semester 2',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A7',  'nama_kriteria' => 'Nilai Rata-rata Semester 3',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A8',  'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 3',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A9',  'nama_kriteria' => 'Absensi Semester 3',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A10', 'nama_kriteria' => 'Nilai Rata-rata Semester 4',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A11', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 4',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A12', 'nama_kriteria' => 'Absensi Semester 4',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A13', 'nama_kriteria' => 'Nilai Rata-rata Semester 5',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A14', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 5',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A15', 'nama_kriteria' => 'Absensi Semester 5',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A16', 'nama_kriteria' => 'Nilai Rata-rata Semester 6',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A17', 'nama_kriteria' => 'Nilai Ekstrakulikuler Semester 6',  'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A18', 'nama_kriteria' => 'Absensi Semester 6',  'jenis' => 'cost',    'created_at' => now(), 'updated_at' => now()],
            ['sekolah_id' => 3, 'kode_kriteria' => 'A19', 'nama_kriteria' => 'Prestasi', 'jenis' => 'benefit', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Bobot SD
        DB::table('bobot_kriteria')->insert([
            ['kriteria_id' => 1,  'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 2,  'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 3,  'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 4,  'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 5,  'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 6,  'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 7,  'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 8,  'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 9,  'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 10, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 11, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 12, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 13, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 14, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 15, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 16, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 17, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 18, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 19, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 20, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 21, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 22, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 23, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 24, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 25, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 26, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 27, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 28, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 29, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 30, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 31, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 32, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 33, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 34, 'bobot' => 0.0400, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 35, 'bobot' => 0.0167, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 36, 'bobot' => 0.0250, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 37, 'bobot' => 0.0196, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Bobot SMP
        DB::table('bobot_kriteria')->insert([
            ['kriteria_id' => 38, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 39, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 40, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 41, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 42, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 43, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 44, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 45, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 46, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 47, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 48, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 49, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 50, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 51, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 52, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 53, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 54, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 55, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 56, 'bobot' => 0.0490, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Bobot SMA
        DB::table('bobot_kriteria')->insert([
            ['kriteria_id' => 57, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 58, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 59, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 60, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 61, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 62, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 63, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 64, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 65, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 66, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 67, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 68, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 69, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 70, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 71, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 72, 'bobot' => 0.0600, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 73, 'bobot' => 0.0492, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 74, 'bobot' => 0.0493, 'created_at' => now(), 'updated_at' => now()],
            ['kriteria_id' => 75, 'bobot' => 0.0490, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // Periode
        DB::table('periode')->insert([
            [
                'periode_id' => 1,
                'tahun_ajaran' => '2024/2025',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Semester
        DB::table('semester')->insert([
            ['nama' => 'Semester 1',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 2',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 3',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 4',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 5',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 6',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 7',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 8',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 9',  'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 10', 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 11', 'created_at' => now(), 'updated_at' => now()],
            ['nama' => 'Semester 12', 'created_at' => now(), 'updated_at' => now()],
        ]);


    }
}
